name: petyatu
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  baseflow_plugin_template: ^2.1.2
  cached_network_image: ^3.2.3
  card_swiper: ^2.0.4
  cloud_firestore: ^4.6.0
  firebase_auth: ^4.4.2
  firebase_core: ^2.10.0
  firebase_messaging: ^14.6.4
  firebase_storage: ^11.2.1
  flutter:
    sdk: flutter
  geocoding: ^2.1.0
  geolocator: ^9.0.2
  http: ^0.13.6
  image_picker: ^0.8.7+5
  intl: ^0.18.1
  path_provider: ^2.0.15
  permission_handler: ^10.4.1
  provider: ^6.0.5
  share: ^2.0.4
  share_plus: ^7.0.2
  url_launcher: ^6.1.11

  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/logo.png
